### ISSUE TITLE
Clean UP & Dockerization eos3cf4

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos3cf4#4]

**Comment by emmakodes** [comment]
Hello @GemmaTuron the model works by installing python-dotenv `pip install python-dotenv`  [here](https://github.com/emmakodes/eos3cf4/actions/runs/5415721888/jobs/9844448155) [here](https://github.com/emmakodes/eos3cf4/actions/runs/5415721882/jobs/9844448166).    The pretrained parameters of the model is hosted on Google Cloud Platform. I am trying to confirm if users of the model don't need to be logged in to Google cloud platform to be able to make use of the model. Someone raised an issue on the model's GitHub page as regard such concern [Cannot download pretrained model](https://github.com/datamol-io/molfeat/issues/61) <br><br>
I don't know if you had to log in to Google Cloud Platform before you were able to make predictions on your PC while incorporating the model.

**Comment by GemmaTuron** [comment]
Hi @emmakodes 
This model is from the MolFeat package of [DataMol](https://molfeat.datamol.io/), which uses a transformer type structure for their models. It is not an issue you do not need to be logged into Google Cloud nor you need to download the checkpoints manually.
I see all the actions run appropriately in the model which is quite new, so I think very little if anything is needed for this model?

**Comment by GemmaTuron** [comment]
Actually if you can just confirm that the model works, we can close this issue because the model seems to be already on the latest eos-template version

**Comment by emmakodes** [comment]
You are right @GemmaTuron the model is on the latest eos-template but missing `upload-model-to-dockerhub.yml` file also when I run the model, it gave an error of `ModuleNotFoundError: No module named dotenv` so I had to include `pip install python-dotenv` to the dockerfile to install `python-dotenv`. I will make a pull request to fix this.

**Comment by GemmaTuron** [comment]
Please when you do also add any .yml file that might be missing, thanks!

**Comment by emmakodes** [comment]
Hello @GemmaTuron I have made PR for this model and you have merged it.

**Comment by GemmaTuron** [comment]
sorry @emmakodes you are right! I've assigned the testing as well
