### ISSUE TITLE
eos3cf4 not fetching correctly - breaks zairachem default config

### ISSUE THREAD

**Issue by JHlozek** [ersilia-os/eos3cf4#7]
Upon a fresh install of zairachem, this eos3cf4 model does not fetch correctly (error log attached), which breaks zairachem.
[eos3cf4_log.txt](https://github.com/ersilia-os/eos3cf4/files/13030322/eos3cf4_log.txt)

The error is consistent across three different machines (2 CentOS and 1 Ubuntu).
I've tried with and without Isaura and docker installed as well as on different versions of the ersilia model hub (v0.1.1, v0.1.24, v0.1.27) and the result is always the same. 

However, I have been able to clone a previous copy of the model from the start of 2023 and the latest ersilia model hub version can serve it and run predictions.

**Comment by GemmaTuron** [comment]
This is now fixed I think in the newest version of Ersilia :)
